# https://github.com/DiffEqML/torchdyn/blob/master/torchdyn/datasets/static_datasets.py
_target_: src.datamodules.distribution_datamodule.SKLearnDataModule
#_target_: src.datamodules.distribution_datamodule.DistributionDataModule

train_val_test_split: [10000, 1000, 1000]
batch_size: 128
num_workers: 0
pin_memory: False

system: "moons"
