_target_: src.datamodules.distribution_datamodule.DistributionDataModule

data_dir: ${data_dir} # data_dir is specified in config.yaml
train_val_test_split: 1000
batch_size: 100
num_workers: 0
pin_memory: False
p: 2
